# Generated by Django 4.2.2 on 2024-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="views",
            field=models.IntegerField(default=0, verbose_name="views"),
        ),
    ]
