# Generated by Django 4.2.2 on 2024-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.TextField(help_text="src", unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="description", max_length=255, null=True
                    ),
                ),
                ("name", models.CharField(help_text="name", max_length=255)),
                (
                    "unique_name",
                    models.CharField(help_text="unique name", max_length=255),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
            ],
            options={
                "verbose_name": "audio",
                "verbose_name_plural": "audio",
                "ordering": ["-update_time"],
            },
        ),
    ]
