# Generated by Django 4.2.2 on 2024-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="views",
            field=models.IntegerField(default=0, verbose_name="views"),
        ),
    ]
