# Generated by Django 4.2.2 on 2024-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="title", max_length=255, unique=True),
                ),
                ("content", models.TextField(help_text="content")),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="author", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="description", max_length=255, null=True
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="update at"),
                ),
            ],
            options={
                "verbose_name": "draft",
                "verbose_name_plural": "draft",
                "ordering": ["-create_time"],
            },
        ),
    ]
